### ISSUE TITLE
How to set this up?

### ISSUE THREAD

**Issue by sirtet** [sgiehl/piwik-plugin-ExcludeByDDNS#1]
First off, thanks for the effort. This is great, i have been looking for such a plugin extensively!
It will give Piwik another USP over Google Analytics, ddns exclusion is not possible there.

I see it's still declared as alpha, but i am eager to help and test it.

I expected that i'd give the plugin my already existing ddns domain name, and it would periodically check the ip of that name.
But it seems this plugin is acting the same as a ddns service, where a ddns client (in my router) announces it's new ip to piwik, whenever it's changed...

The problem with that is, on my router i can set up only one DDNS service at a time. which is already occupied by another ddns service, which i need for stuff like VPN. All routers i know allow only one DDNS setup.
So this only works for people who can set up a 2nd DDNS-client, eg. in a NAS.
I tried that, but my NAS does not allow custom settings for DDNS, so that's another problem.
(it would allow multiple DDNS services in parallel).
My router does allow the custom update URL, so i entered the piwik url there, for testing.

But there's no way to tell if things are working (other than checking if i still get tracked).
I would expect the plugin to tell me if it's receiving updates. Like what the current IP is and when it did get that.
Also, maybe it should report back to the client if the submitted data was accepted (or does it already?).

I suspect the update-URL 
`http://piwik.url/index.php?module=ExcludeByDDNS&action=update&token_auth={token_auth}`
is not correctly set by me. Off course i did replace _piwik.url_ with the url for my personal piwik install, but doesn't the  `{token_auth}` part need to be replaced with something too?
Or is it a part that the client will substitute with something? my other DDNS- update-url has different brackets for that: `https://update.twodns.de/update?hostname=<domain>&ip=<ipaddr>`

Now is there a way to tell if this setup works?
for other dns-services, the router sees if it works, and displays the status. I don't know if that status is determined by a ping to the name and comparing the ip, or if it's from an http response on to the update-url. But with the piwik-URL, it says "not connected".

**Comment by sgiehl** [comment]
you need to replace the {token_auth} with your users API token.
I will make some thoughts on your other notes and create follow up tickets with according feature requests

**Comment by sirtet** [comment]
Ok, great! After puttnig my auth-key into the update-url it workded.
I used the visitor log to confirm i did not see my own visits when the plugin was active. I also counter-checked that i saw them after disabling the plugin.

BIG thanks.
