### ISSUE TITLE
strange problems with BotTracker

### ISSUE THREAD

**Issue by Thomas--F** [sgiehl/piwik-plugin-ExcludeByDDNS#16]
Hi Stefan,

one user reported a strange behavior of this plugin together with the BotTracker-plugin:
https://github.com/Thomas--F/BotTracker/issues/33
It seems, the execution of the task "Piwik\Plugins\ExcludeByDDNS\Tasks.updateIPs" deactivates the BotTracker-plugin.
I cannot reproduce the issue and as far as I can see, there is no way to deactivate a plugin from the task of another plugin.
Can you take a look at it?

**Comment by sgiehl** [comment]
I can't see any possibility that the cron task could disable another plugin.
The Job updates a database record (with the new IPs) and clears the Piwik Cache.
Maybe clearing the cache causes the issue, but that shouldn't be a fault of my plugin
