### ISSUE TITLE
Ensure correct response on DDNS update

### ISSUE THREAD

**Issue by sgiehl** [sgiehl/piwik-plugin-ExcludeByDDNS#4]
Routers are displaying the current status of a DDNS-Service.
That may be based on the Response(-Code) of the update call.

We need to ensure, that the response matches the expected behaviour.

refs #1

**Comment by sirtet** [comment]
I think there is a piwik bug preventing correct operation: When requesting a piwik-page without being authenticated, it returns the login-form with status code 200 ok. Shouldn't that be a delivered with a 403?
Then i guess that would also be the correct response for a DDNS update request with an incorrect auth token.
I tried to find a rfc or similar for DDNS, but did not find anything.

**Comment by sgiehl** [comment]
haven't found an rfc either. So I don't know how to solve this issue.
For having a 403 status for the login page, we would need an issue for piwik

**Comment by sirtet** [comment]
Opened #7293 on piwik...

**Comment by sirtet** [comment]
Wrote a mail to AVM, to see if we can get infos on what answers/statuscodes a FritzBox expects.

**Comment by sgiehl** [comment]
:+1: if there's anything I need to do within the plugin, please reopen this ticket

**Comment by sirtet** [comment]
About expected answers from DDNS clients:
AVM referred to their Dev support:
http://avm.de/service/schnittstellen/
there's one Doc. about DDNS,
http://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_remoteSCPD.pdf
but it talks about the status values only, not how they are retrieved...

Also, the lead dev. from two-dns answered:

> Hi there,
> 
> unfortunately every service does their own thing. AFAIK there is an RFC, but it's not widely adopted > > last time we've checked.
> 
> Our API is documented over at http://api.twodns.de, that should give a few pointers.

Their API documentation sheds some light, but it's not clear how much the answers from other services differ, so it would be more interesting finding out what a FritzBox expects when using  user defined configuration.
Also, finding the mentioned RFC might still help some.
