### ISSUE TITLE
Hostname-based updating is not working

### ISSUE THREAD

**Issue by sirtet** [sgiehl/piwik-plugin-ExcludeByDDNS#7]
After checking out the commit latest b419e675a12ef1bbeb07d85be1926c58fcb7b426
The settings screen introduced here showed the correct IP retrieved by the DDNS client. 
But switching to hostname-based ip updating does not.
To "switch", i just added the hostname which correctly points to the Updated IP, but even after hours the excluded IP is still the old one.

I'd suggest to show the last update-time of the IP too, for easyer debuging.

**Comment by sirtet** [comment]
PS:
To easyer test the latest commits, adding releases would help.
As the module is marked as alpha, i guess it wont hurt to 'release' untested versions.
But people could test via plugin re-install, vs currently only manual/git download.

**Comment by sgiehl** [comment]
Updates are done using a scheduled task. Maybe it hasn't been executed. If you would like to see when it was done last, install ScheduledTasks plugin from the market place.
To ensure Tasks are executed continuously you may need to set up a cron for it.

**Comment by sirtet** [comment]
The Plugin is called TasksTimetable. I can now see the update task, but big negative times, seems no tasks are executed at all. I expected piwik would use the tracking calls to run tasks...
I did not find out yet how to set up the cron's.

Maybe the plugin should check if tasks work, if it relies on it?

**Comment by sgiehl** [comment]
You can run scheduled tasks using piwik console:
`./console core:run-scheduled-tasks`

**Comment by sirtet** [comment]
No tasks run at all, so it's  a core problem, closing here.
