### ISSUE TITLE
Add Link to settings page

### ISSUE THREAD

**Issue by sirtet** [sgiehl/piwik-plugin-ExcludeByDDNS#8]
![piwik-plugin-settings-link](https://cloud.githubusercontent.com/assets/3509308/6348824/ec46d20c-bc23-11e4-9fa9-d33cd38253f9.jpg)

**Comment by sgiehl** [comment]
Sorry, that is not possible. Piwik only displays that link for plugins using the settings options given by piwik. As I need to use some custom stuff there's no way to add that link.
I could add that link to the plugin description instead.

**Comment by sgiehl** [comment]
Sry. Adding it there isn't possible, aswell. Maybe there is a way to do that in a later piwik version.
Closing this issue for now.

**Comment by sirtet** [comment]
But a textual description where the settings are to be found should be in the description...

**Comment by sgiehl** [comment]
That can only been seen by the superuser as other users don't have access to plugin management.
As this plugin provides settings per user, the settings can be found in the personal settings of each user.
