### ISSUE TITLE
Exclude multiple IP's

### ISSUE THREAD

**Issue by sirtet** [sgiehl/piwik-plugin-ExcludeByDDNS#9]
Multiple static IPs can be added for exclusion, which is needed for eg. Company branches or home-offices.
Such an option would be nice for ddns too...
Not sure if it already works via hostname lookup, the settings seem to be per-user? Or would resolved ips from different settings currently overwrite eachother?

**Comment by sgiehl** [comment]
Excluded IP is per user

**Comment by sirtet** [comment]
So, how is that to be understood?
Generally, i think/thought excluded IP's are not tracked at all. Or are they tracked, but not in the reports if viewed by user X?

What's the idea behind having exclusion per-user anyways? Core's static IP exclusion is global or per-website.
Is it just an easy way to exclude more than one IP? For users, it might be somewhat misleading, if it works different than the core IP exclusion.

**Comment by sgiehl** [comment]
You got me wrong. Each user is able to completely exclude one IP with DDNS.

**Comment by sirtet** [comment]
I see. 
What's the idea behind having exclusion per-user? Core's static IP exclusion is global or per-website.
Is it just an easy way to exclude more than one IP? 
For users, it might be somewhat misleading, as it works different than the core IP exclusion. You need to know all users settings to understand what's going on.

**Comment by sgiehl** [comment]
Excluded IPs are excluded global. That can be done in global settings aswell. So I think it shouldn't be missleading.
Each user is able to exclude on IP. That's what I meant with 'per-user'. And I don't think a user needs to exclude more than one IP. If so, he could create a new piwik account and use that only for another IP exclusion.

**Comment by sirtet** [comment]
Well, i assumed that typically, there will be just one admin/webmaster, who has to exclude maybe multiple home-offices or branches, not multiple users who all maintain their own setup.
And, with per-user exclusion, it's hard to get an overview of all excluded ip's, where i think, working with piwik data will be typically be done by just one expert...
Thus i'd prefer the plugin to work the same way as core ip exclusion.
